[2025-10-24T00:59:05.902+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_pipeline_dag.collect_bluebikes scheduled__2025-10-23T00:00:00+00:00 [queued]>
[2025-10-24T00:59:05.908+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_pipeline_dag.collect_bluebikes scheduled__2025-10-23T00:00:00+00:00 [queued]>
[2025-10-24T00:59:05.908+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-10-24T00:59:05.909+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-10-24T00:59:05.909+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-10-24T00:59:05.916+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): collect_bluebikes> on 2025-10-23 00:00:00+00:00
[2025-10-24T00:59:05.919+0000] {standard_task_runner.py:55} INFO - Started process 146 to run task
[2025-10-24T00:59:05.921+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_dag', 'collect_bluebikes', 'scheduled__2025-10-23T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_dag.py', '--cfg-path', '/tmp/tmpvlryp_4h']
[2025-10-24T00:59:05.922+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask collect_bluebikes
[2025-10-24T00:59:06.000+0000] {task_command.py:388} INFO - Running <TaskInstance: data_pipeline_dag.collect_bluebikes scheduled__2025-10-23T00:00:00+00:00 [running]> on host 30bb99067add
[2025-10-24T00:59:06.050+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_pipeline_dag
AIRFLOW_CTX_TASK_ID=collect_bluebikes
AIRFLOW_CTX_EXECUTION_DATE=2025-10-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-23T00:00:00+00:00
[2025-10-24T00:59:06.054+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: collect_bluebikes_data() missing 5 required positional arguments: 'index_url', 'years', 'download_dir', 'parquet_dir', and 'log_path'
[2025-10-24T00:59:06.064+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=data_pipeline_dag, task_id=collect_bluebikes, execution_date=20251023T000000, start_date=20251024T005905, end_date=20251024T005906
[2025-10-24T00:59:06.074+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 13 for task collect_bluebikes (collect_bluebikes_data() missing 5 required positional arguments: 'index_url', 'years', 'download_dir', 'parquet_dir', and 'log_path'; 146)
[2025-10-24T00:59:06.100+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-10-24T00:59:06.132+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
