[2025-10-23T23:24:05.670+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:24:05.671+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:24:05.671+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:24:05.671+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:24:05.680+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:24:05.679+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 6, in <module>
    from datapipeline import (
ModuleNotFoundError: No module named 'datapipeline'
[2025-10-23T23:24:05.680+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:24:05.692+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.024 seconds
[2025-10-23T23:24:35.889+0000] {processor.py:153} INFO - Started process (PID=103) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:24:35.889+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:24:35.890+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:24:35.890+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:24:35.895+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:24:35.894+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 6, in <module>
    from datapipeline import (
ModuleNotFoundError: No module named 'datapipeline'
[2025-10-23T23:24:35.895+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:24:35.904+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.017 seconds
[2025-10-23T23:25:06.140+0000] {processor.py:153} INFO - Started process (PID=144) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:25:06.141+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:25:06.142+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:25:06.142+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:25:06.152+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:25:06.151+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 6, in <module>
    from datapipeline import (
ModuleNotFoundError: No module named 'datapipeline'
[2025-10-23T23:25:06.153+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:25:06.166+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.029 seconds
[2025-10-23T23:26:04.718+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:26:04.718+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:26:04.719+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:26:04.719+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:26:04.728+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:26:04.728+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 6, in <module>
    from datapipeline import (
ModuleNotFoundError: No module named 'datapipeline'
[2025-10-23T23:26:04.729+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:26:04.736+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.020 seconds
[2025-10-23T23:26:34.951+0000] {processor.py:153} INFO - Started process (PID=103) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:26:34.952+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:26:34.953+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:26:34.953+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:26:34.961+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:26:34.960+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 6, in <module>
    from datapipeline import (
ModuleNotFoundError: No module named 'datapipeline'
[2025-10-23T23:26:34.962+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:26:34.975+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.030 seconds
[2025-10-23T23:27:05.235+0000] {processor.py:153} INFO - Started process (PID=144) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:27:05.236+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:27:05.236+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:27:05.236+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:27:05.245+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:27:05.244+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 6, in <module>
    from datapipeline import (
ModuleNotFoundError: No module named 'datapipeline'
[2025-10-23T23:27:05.245+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:27:05.255+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.024 seconds
[2025-10-23T23:27:35.515+0000] {processor.py:153} INFO - Started process (PID=205) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:27:35.516+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:27:35.517+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:27:35.517+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:27:35.532+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:27:35.528+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 6, in <module>
    from datapipeline import (
ModuleNotFoundError: No module named 'datapipeline'
[2025-10-23T23:27:35.533+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:27:35.561+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.050 seconds
[2025-10-23T23:27:46.595+0000] {processor.py:153} INFO - Started process (PID=226) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:27:46.596+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:27:46.597+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:27:46.597+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:27:46.604+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:27:46.603+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 4, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), "..", "scripts"))
NameError: name 'sys' is not defined
[2025-10-23T23:27:46.604+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:27:46.618+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.025 seconds
[2025-10-23T23:28:19.320+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:28:19.320+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:28:19.321+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:28:19.321+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:28:19.332+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:28:19.331+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 4, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), "..", "scripts"))
NameError: name 'sys' is not defined
[2025-10-23T23:28:19.332+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:28:19.343+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.025 seconds
[2025-10-23T23:28:49.614+0000] {processor.py:153} INFO - Started process (PID=103) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:28:49.615+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:28:49.616+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:28:49.616+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:28:49.624+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:28:49.623+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 4, in <module>
    sys.path.append(os.path.join(os.path.dirname(__file__), "..", "scripts"))
NameError: name 'sys' is not defined
[2025-10-23T23:28:49.624+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:28:49.638+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.028 seconds
[2025-10-23T23:29:02.746+0000] {processor.py:153} INFO - Started process (PID=124) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:29:02.747+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:29:02.748+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:29:02.748+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:29:02.848+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:29:02.846+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 4, in <module>
    from bluebikes_data_helpers.download_data import find_zip_links, download_zips
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/download_data.py", line 12, in <module>
    def _guess_s3_bucket(index_url: str) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
[2025-10-23T23:29:02.848+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:29:02.856+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.114 seconds
[2025-10-23T23:29:29.961+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:29:29.962+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:29:29.963+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:29:29.962+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:29:30.045+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:29:30.044+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 4, in <module>
    from bluebikes_data_helpers.download_data import find_zip_links, download_zips
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/download_data.py", line 12, in <module>
    def _guess_s3_bucket(index_url: str) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
[2025-10-23T23:29:30.046+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:29:30.055+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.096 seconds
[2025-10-23T23:30:00.195+0000] {processor.py:153} INFO - Started process (PID=103) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:30:00.196+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:30:00.196+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:30:00.196+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:30:00.252+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:30:00.251+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 4, in <module>
    from bluebikes_data_helpers.download_data import find_zip_links, download_zips
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/download_data.py", line 12, in <module>
    def _guess_s3_bucket(index_url: str) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
[2025-10-23T23:30:00.253+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:30:00.260+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.068 seconds
[2025-10-23T23:30:30.470+0000] {processor.py:153} INFO - Started process (PID=144) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:30:30.471+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:30:30.471+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:30:30.471+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:30:30.558+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:30:30.555+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 4, in <module>
    from bluebikes_data_helpers.download_data import find_zip_links, download_zips
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/download_data.py", line 12, in <module>
    def _guess_s3_bucket(index_url: str) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
[2025-10-23T23:30:30.558+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:30:30.582+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.112 seconds
[2025-10-23T23:31:00.668+0000] {processor.py:153} INFO - Started process (PID=204) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:31:00.668+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:31:00.669+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:31:00.669+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:31:00.723+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:31:00.721+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 4, in <module>
    from bluebikes_data_helpers.download_data import find_zip_links, download_zips
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/download_data.py", line 12, in <module>
    def _guess_s3_bucket(index_url: str) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
[2025-10-23T23:31:00.723+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:31:00.730+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.066 seconds
[2025-10-23T23:31:30.926+0000] {processor.py:153} INFO - Started process (PID=265) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:31:30.927+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:31:30.928+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:31:30.928+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:31:30.997+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:31:30.994+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 4, in <module>
    from bluebikes_data_helpers.download_data import find_zip_links, download_zips
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/download_data.py", line 12, in <module>
    def _guess_s3_bucket(index_url: str) -> Optional[str]:
NameError: name 'Optional' is not defined
[2025-10-23T23:31:30.998+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:31:31.012+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.089 seconds
[2025-10-23T23:31:54.568+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:31:54.568+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:31:54.569+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:31:54.569+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:31:54.646+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:31:54.645+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 4, in <module>
    from bluebikes_data_helpers.download_data import find_zip_links, download_zips
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/download_data.py", line 12, in <module>
    def _guess_s3_bucket(index_url: str) -> Optional[str]:
NameError: name 'Optional' is not defined
[2025-10-23T23:31:54.646+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:31:54.655+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.089 seconds
[2025-10-23T23:32:24.814+0000] {processor.py:153} INFO - Started process (PID=103) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:32:24.815+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:32:24.816+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:32:24.816+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:32:24.875+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:32:24.873+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 4, in <module>
    from bluebikes_data_helpers.download_data import find_zip_links, download_zips
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/download_data.py", line 12, in <module>
    def _guess_s3_bucket(index_url: str) -> Optional[str]:
NameError: name 'Optional' is not defined
[2025-10-23T23:32:24.875+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:32:24.882+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.071 seconds
[2025-10-23T23:33:23.758+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:33:23.759+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:33:23.759+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:33:23.759+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:33:23.846+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:33:23.844+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 4, in <module>
    from bluebikes_data_helpers.download_data import find_zip_links, download_zips
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/download_data.py", line 35, in <module>
    def _list_s3_zip_urls(bucket: str) -> list[str]:
TypeError: 'type' object is not subscriptable
[2025-10-23T23:33:23.846+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:33:23.853+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.097 seconds
[2025-10-23T23:33:53.998+0000] {processor.py:153} INFO - Started process (PID=103) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:33:53.999+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:33:54.000+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:33:54.000+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:33:54.061+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:33:54.059+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 4, in <module>
    from bluebikes_data_helpers.download_data import find_zip_links, download_zips
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/download_data.py", line 35, in <module>
    def _list_s3_zip_urls(bucket: str) -> list[str]:
TypeError: 'type' object is not subscriptable
[2025-10-23T23:33:54.061+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:33:54.068+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.073 seconds
[2025-10-23T23:34:24.268+0000] {processor.py:153} INFO - Started process (PID=144) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:34:24.268+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:34:24.268+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:34:24.268+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:34:24.312+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:34:24.311+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 4, in <module>
    from bluebikes_data_helpers.download_data import find_zip_links, download_zips
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/download_data.py", line 35, in <module>
    def _list_s3_zip_urls(bucket: str) -> list[str]:
TypeError: 'type' object is not subscriptable
[2025-10-23T23:34:24.313+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:34:24.320+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.054 seconds
[2025-10-23T23:34:54.562+0000] {processor.py:153} INFO - Started process (PID=205) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:34:54.563+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:34:54.564+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:34:54.564+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:34:54.620+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:34:54.619+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 4, in <module>
    from bluebikes_data_helpers.download_data import find_zip_links, download_zips
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/download_data.py", line 35, in <module>
    def _list_s3_zip_urls(bucket: str) -> list[str]:
TypeError: 'type' object is not subscriptable
[2025-10-23T23:34:54.620+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:34:54.628+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.069 seconds
[2025-10-23T23:35:44.465+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:35:44.466+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:35:44.470+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:35:44.470+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:35:44.547+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:35:44.546+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 4, in <module>
    from bluebikes_data_helpers.download_data import find_zip_links, download_zips
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/download_data.py", line 67, in <module>
    def find_zip_links(index_url: str, names: list[str]) -> list[str]:
TypeError: 'type' object is not subscriptable
[2025-10-23T23:35:44.548+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:35:44.556+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.093 seconds
[2025-10-23T23:36:14.681+0000] {processor.py:153} INFO - Started process (PID=103) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:36:14.682+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:36:14.682+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:36:14.682+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:36:14.737+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:36:14.736+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 4, in <module>
    from bluebikes_data_helpers.download_data import find_zip_links, download_zips
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/download_data.py", line 67, in <module>
    def find_zip_links(index_url: str, names: list[str]) -> list[str]:
TypeError: 'type' object is not subscriptable
[2025-10-23T23:36:14.737+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:36:14.745+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.066 seconds
[2025-10-23T23:36:59.464+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:36:59.464+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:36:59.466+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:36:59.466+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:36:59.544+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:36:59.542+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 4, in <module>
    from bluebikes_data_helpers.download_data import find_zip_links, download_zips
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/download_data.py", line 67, in <module>
    def find_zip_links(index_url: str, names: list[str]) -> List[str]:
TypeError: 'type' object is not subscriptable
[2025-10-23T23:36:59.544+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:36:59.556+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.094 seconds
[2025-10-23T23:37:29.696+0000] {processor.py:153} INFO - Started process (PID=103) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:37:29.697+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:37:29.698+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:37:29.698+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:37:29.763+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:37:29.760+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 4, in <module>
    from bluebikes_data_helpers.download_data import find_zip_links, download_zips
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/download_data.py", line 67, in <module>
    def find_zip_links(index_url: str, names: list[str]) -> List[str]:
TypeError: 'type' object is not subscriptable
[2025-10-23T23:37:29.764+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:37:29.777+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.085 seconds
[2025-10-23T23:37:59.979+0000] {processor.py:153} INFO - Started process (PID=144) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:37:59.979+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:37:59.979+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:37:59.979+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:38:00.023+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:38:00.021+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 4, in <module>
    from bluebikes_data_helpers.download_data import find_zip_links, download_zips
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/download_data.py", line 67, in <module>
    def find_zip_links(index_url: str, names: list[str]) -> List[str]:
TypeError: 'type' object is not subscriptable
[2025-10-23T23:38:00.023+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:38:00.031+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.053 seconds
[2025-10-23T23:38:30.237+0000] {processor.py:153} INFO - Started process (PID=205) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:38:30.238+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:38:30.239+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:38:30.239+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:38:30.299+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:38:30.297+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 4, in <module>
    from bluebikes_data_helpers.download_data import find_zip_links, download_zips
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/download_data.py", line 67, in <module>
    def find_zip_links(index_url: str, names: list[str]) -> List[str]:
TypeError: 'type' object is not subscriptable
[2025-10-23T23:38:30.299+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:38:30.309+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.075 seconds
[2025-10-23T23:39:21.902+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:39:21.905+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:39:21.906+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:39:21.906+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:39:21.990+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:39:21.988+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 5, in <module>
    from bluebikes_data_helpers.read_zips import save_year_to_parquet
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/read_zips.py", line 82
    os.makedirs(out_dir := Path(out_dir), exist_ok=True)
                        ^
SyntaxError: invalid syntax
[2025-10-23T23:39:21.990+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:39:21.999+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.099 seconds
[2025-10-23T23:39:52.138+0000] {processor.py:153} INFO - Started process (PID=103) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:39:52.139+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:39:52.140+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:39:52.140+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:39:52.205+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:39:52.203+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 5, in <module>
    from bluebikes_data_helpers.read_zips import save_year_to_parquet
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/read_zips.py", line 82
    os.makedirs(out_dir := Path(out_dir), exist_ok=True)
                        ^
SyntaxError: invalid syntax
[2025-10-23T23:39:52.205+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:39:52.214+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.080 seconds
[2025-10-23T23:40:22.420+0000] {processor.py:153} INFO - Started process (PID=153) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:40:22.423+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:40:22.423+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:40:22.423+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:40:22.504+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:40:22.502+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 5, in <module>
    from bluebikes_data_helpers.read_zips import save_year_to_parquet
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/read_zips.py", line 82
    os.makedirs(out_dir := Path(out_dir), exist_ok=True)
                        ^
SyntaxError: invalid syntax
[2025-10-23T23:40:22.504+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:40:22.512+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.094 seconds
[2025-10-23T23:40:52.703+0000] {processor.py:153} INFO - Started process (PID=205) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:40:52.703+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:40:52.704+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:40:52.704+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:40:52.762+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:40:52.761+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 5, in <module>
    from bluebikes_data_helpers.read_zips import save_year_to_parquet
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/read_zips.py", line 82
    os.makedirs(out_dir := Path(out_dir), exist_ok=True)
                        ^
SyntaxError: invalid syntax
[2025-10-23T23:40:52.763+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:40:52.771+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.071 seconds
[2025-10-23T23:41:22.935+0000] {processor.py:153} INFO - Started process (PID=266) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:41:22.936+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:41:22.936+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:41:22.936+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:41:22.988+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:41:22.987+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 5, in <module>
    from bluebikes_data_helpers.read_zips import save_year_to_parquet
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/read_zips.py", line 82
    os.makedirs(out_dir := Path(out_dir), exist_ok=True)
                        ^
SyntaxError: invalid syntax
[2025-10-23T23:41:22.988+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:41:22.996+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.063 seconds
[2025-10-23T23:41:53.209+0000] {processor.py:153} INFO - Started process (PID=327) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:41:53.210+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:41:53.210+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:41:53.210+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:41:53.264+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:41:53.262+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 5, in <module>
    from bluebikes_data_helpers.read_zips import save_year_to_parquet
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/read_zips.py", line 82
    os.makedirs(out_dir := Path(out_dir), exist_ok=True)
                        ^
SyntaxError: invalid syntax
[2025-10-23T23:41:53.264+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:41:53.271+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.065 seconds
[2025-10-23T23:42:23.462+0000] {processor.py:153} INFO - Started process (PID=388) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:42:23.462+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:42:23.463+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:42:23.462+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:42:24.096+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:42:24.095+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 5, in <module>
    from bluebikes_data_helpers.read_zips import save_year_to_parquet
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/read_zips.py", line 14, in <module>
    from bluebikes_data_helpers.record_file import log_file_status
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/record_file.py", line 5, in <module>
    def log_file_status(log_path: str | Path, filename: str, status: bool):
TypeError: unsupported operand type(s) for |: 'type' and 'type'
[2025-10-23T23:42:24.096+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:42:24.102+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.642 seconds
[2025-10-23T23:43:09.384+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:43:09.385+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:43:09.388+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:43:09.388+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:43:10.009+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:43:10.008+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 5, in <module>
    from bluebikes_data_helpers.read_zips import save_year_to_parquet
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/read_zips.py", line 14, in <module>
    from bluebikes_data_helpers.record_file import log_file_status
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/record_file.py", line 5, in <module>
    def log_file_status(log_path: str | Path, filename: str, status: bool):
TypeError: unsupported operand type(s) for |: 'type' and 'type'
[2025-10-23T23:43:10.010+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:43:10.018+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.637 seconds
[2025-10-23T23:43:40.306+0000] {processor.py:153} INFO - Started process (PID=104) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:43:40.307+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:43:40.308+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:43:40.308+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:43:40.547+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:43:40.546+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 5, in <module>
    from bluebikes_data_helpers.read_zips import save_year_to_parquet
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/read_zips.py", line 14, in <module>
    from bluebikes_data_helpers.record_file import log_file_status
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/record_file.py", line 5, in <module>
    def log_file_status(log_path: str | Path, filename: str, status: bool):
TypeError: unsupported operand type(s) for |: 'type' and 'type'
[2025-10-23T23:43:40.547+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:43:40.553+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.252 seconds
[2025-10-23T23:44:10.775+0000] {processor.py:153} INFO - Started process (PID=166) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:44:10.776+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:44:10.776+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:44:10.776+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:44:10.979+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:44:10.978+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 5, in <module>
    from bluebikes_data_helpers.read_zips import save_year_to_parquet
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/read_zips.py", line 14, in <module>
    from bluebikes_data_helpers.record_file import log_file_status
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/record_file.py", line 5, in <module>
    def log_file_status(log_path: str | Path, filename: str, status: bool):
TypeError: unsupported operand type(s) for |: 'type' and 'type'
[2025-10-23T23:44:10.979+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:44:10.986+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.212 seconds
[2025-10-23T23:44:41.036+0000] {processor.py:153} INFO - Started process (PID=208) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:44:41.037+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:44:41.038+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:44:41.037+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:44:41.358+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:44:41.357+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 5, in <module>
    from bluebikes_data_helpers.read_zips import save_year_to_parquet
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/read_zips.py", line 14, in <module>
    from bluebikes_data_helpers.record_file import log_file_status
  File "/opt/airflow/dags/../scripts/bluebikes_data_helpers/record_file.py", line 5, in <module>
    def log_file_status(log_path: str | Path, filename: str, status: bool):
TypeError: unsupported operand type(s) for |: 'type' and 'type'
[2025-10-23T23:44:41.358+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:44:41.366+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.333 seconds
[2025-10-23T23:45:11.457+0000] {processor.py:153} INFO - Started process (PID=270) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:45:11.459+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:45:11.460+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:45:11.460+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:45:11.772+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:45:11.771+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 9, in <module>
    from school_noaa_data_collectors.NOAA_DataAcq import NOAA
  File "/opt/airflow/dags/../scripts/school_noaa_data_collectors/NOAA_DataAcq.py", line 4, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2025-10-23T23:45:11.772+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:45:11.780+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.329 seconds
[2025-10-23T23:45:50.250+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:45:50.251+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:45:50.252+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:45:50.252+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:45:50.928+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:45:50.927+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 9, in <module>
    from school_noaa_data_collectors.NOAA_DataAcq import NOAA
  File "/opt/airflow/dags/../scripts/school_noaa_data_collectors/NOAA_DataAcq.py", line 4, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2025-10-23T23:45:50.928+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:45:50.937+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.689 seconds
[2025-10-23T23:46:21.206+0000] {processor.py:153} INFO - Started process (PID=104) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:46:21.207+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:46:21.208+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:46:21.208+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:46:21.480+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:46:21.479+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 9, in <module>
    from school_noaa_data_collectors.NOAA_DataAcq import NOAA
  File "/opt/airflow/dags/../scripts/school_noaa_data_collectors/NOAA_DataAcq.py", line 4, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2025-10-23T23:46:21.480+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:46:21.487+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.284 seconds
[2025-10-23T23:46:51.790+0000] {processor.py:153} INFO - Started process (PID=166) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:46:51.791+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:46:51.791+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:46:51.791+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:46:52.031+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:46:52.030+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 9, in <module>
    from school_noaa_data_collectors.NOAA_DataAcq import NOAA
  File "/opt/airflow/dags/../scripts/school_noaa_data_collectors/NOAA_DataAcq.py", line 4, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2025-10-23T23:46:52.031+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:46:52.038+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.249 seconds
[2025-10-23T23:47:22.311+0000] {processor.py:153} INFO - Started process (PID=208) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:47:22.312+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:47:22.313+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:47:22.313+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:47:22.546+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:47:22.545+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 9, in <module>
    from school_noaa_data_collectors.NOAA_DataAcq import NOAA
  File "/opt/airflow/dags/../scripts/school_noaa_data_collectors/NOAA_DataAcq.py", line 4, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2025-10-23T23:47:22.546+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:47:22.553+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.245 seconds
[2025-10-23T23:47:52.607+0000] {processor.py:153} INFO - Started process (PID=269) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:47:52.608+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:47:52.609+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:47:52.609+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:47:52.820+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:47:52.819+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 9, in <module>
    from school_noaa_data_collectors.NOAA_DataAcq import NOAA
  File "/opt/airflow/dags/../scripts/school_noaa_data_collectors/NOAA_DataAcq.py", line 4, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2025-10-23T23:47:52.820+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:47:52.826+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.223 seconds
[2025-10-23T23:48:23.092+0000] {processor.py:153} INFO - Started process (PID=331) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:48:23.093+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:48:23.093+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:48:23.093+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:48:23.362+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:48:23.361+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 9, in <module>
    from school_noaa_data_collectors.NOAA_DataAcq import NOAA
  File "/opt/airflow/dags/../scripts/school_noaa_data_collectors/NOAA_DataAcq.py", line 4, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2025-10-23T23:48:23.362+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:48:23.368+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.279 seconds
[2025-10-23T23:49:15.107+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:49:15.108+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:49:15.108+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:49:15.108+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:49:15.756+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:49:15.755+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 9, in <module>
    from school_noaa_data_collectors.NOAA_DataAcq import NOAA
  File "/opt/airflow/dags/../scripts/school_noaa_data_collectors/NOAA_DataAcq.py", line 4, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2025-10-23T23:49:15.757+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:49:15.765+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.660 seconds
[2025-10-23T23:49:46.037+0000] {processor.py:153} INFO - Started process (PID=104) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:49:46.041+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:49:46.042+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:49:46.042+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:49:46.324+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:49:46.323+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 9, in <module>
    from school_noaa_data_collectors.NOAA_DataAcq import NOAA
  File "/opt/airflow/dags/../scripts/school_noaa_data_collectors/NOAA_DataAcq.py", line 4, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2025-10-23T23:49:46.324+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:49:46.331+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.299 seconds
[2025-10-23T23:50:16.592+0000] {processor.py:153} INFO - Started process (PID=166) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:50:16.593+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:50:16.594+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:50:16.593+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:50:16.872+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:50:16.871+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 9, in <module>
    from school_noaa_data_collectors.NOAA_DataAcq import NOAA
  File "/opt/airflow/dags/../scripts/school_noaa_data_collectors/NOAA_DataAcq.py", line 4, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2025-10-23T23:50:16.872+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:50:16.879+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.292 seconds
[2025-10-23T23:51:12.558+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:51:12.559+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:51:12.560+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:51:12.560+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:51:13.246+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:51:13.245+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 9, in <module>
    from school_noaa_data_collectors.NOAA_DataAcq import NOAA
  File "/opt/airflow/dags/../scripts/school_noaa_data_collectors/NOAA_DataAcq.py", line 4, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2025-10-23T23:51:13.247+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:51:13.259+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.703 seconds
[2025-10-23T23:51:43.554+0000] {processor.py:153} INFO - Started process (PID=104) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:51:43.555+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:51:43.556+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:51:43.556+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:51:43.828+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:51:43.827+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 9, in <module>
    from school_noaa_data_collectors.NOAA_DataAcq import NOAA
  File "/opt/airflow/dags/../scripts/school_noaa_data_collectors/NOAA_DataAcq.py", line 4, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2025-10-23T23:51:43.828+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:51:43.835+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.286 seconds
[2025-10-23T23:53:12.326+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:53:12.327+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:53:12.327+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:53:12.327+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:53:12.988+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:53:12.987+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 9, in <module>
    from school_noaa_data_collectors.NOAA_DataAcq import NOAA
  File "/opt/airflow/dags/../scripts/school_noaa_data_collectors/NOAA_DataAcq.py", line 4, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2025-10-23T23:53:12.989+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:53:12.997+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.674 seconds
[2025-10-23T23:53:43.253+0000] {processor.py:153} INFO - Started process (PID=104) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:53:43.254+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:53:43.255+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:53:43.255+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:53:43.557+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:53:43.556+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 9, in <module>
    from school_noaa_data_collectors.NOAA_DataAcq import NOAA
  File "/opt/airflow/dags/../scripts/school_noaa_data_collectors/NOAA_DataAcq.py", line 4, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2025-10-23T23:53:43.557+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:53:43.565+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.314 seconds
[2025-10-23T23:54:13.802+0000] {processor.py:153} INFO - Started process (PID=166) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:54:13.802+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:54:13.803+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:54:13.802+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:54:14.034+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:54:14.033+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 9, in <module>
    from school_noaa_data_collectors.NOAA_DataAcq import NOAA
  File "/opt/airflow/dags/../scripts/school_noaa_data_collectors/NOAA_DataAcq.py", line 4, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2025-10-23T23:54:14.034+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:54:14.042+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.242 seconds
[2025-10-23T23:55:08.596+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:55:08.596+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:55:08.597+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:55:08.597+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:55:09.193+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:55:09.192+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 9, in <module>
    from school_noaa_data_collectors.NOAA_DataAcq import NOAA
  File "/opt/airflow/dags/../scripts/school_noaa_data_collectors/NOAA_DataAcq.py", line 4, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2025-10-23T23:55:09.193+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:55:09.201+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.607 seconds
[2025-10-23T23:55:39.432+0000] {processor.py:153} INFO - Started process (PID=104) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:55:39.434+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:55:39.435+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:55:39.435+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:55:39.705+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:55:39.704+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 9, in <module>
    from school_noaa_data_collectors.NOAA_DataAcq import NOAA
  File "/opt/airflow/dags/../scripts/school_noaa_data_collectors/NOAA_DataAcq.py", line 4, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2025-10-23T23:55:39.705+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:55:39.712+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.283 seconds
[2025-10-23T23:59:58.501+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:59:58.502+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-23T23:59:58.504+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:59:58.504+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:59:59.118+0000] {logging_mixin.py:137} INFO - [2025-10-23T23:59:59.117+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 9, in <module>
    from school_noaa_data_collectors.NOAA_DataAcq import NOAA
  File "/opt/airflow/dags/../scripts/school_noaa_data_collectors/NOAA_DataAcq.py", line 4, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2025-10-23T23:59:59.118+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-23T23:59:59.126+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.627 seconds
